# Config file for automatic testing at travis-ci.org

language: python

matrix:
  include:
     - python: 3.8-dev
       dist: xenial
     - python: 3.7
       dist: xenial
     - python: 3.6
       dist: xenial
     - python: 3.5
       dist: xenial
     - python: 3.4
       dist: xenial
     - python: 2.7
       dist: xenial
     - python: 2.6
       dist: trusty
  allow_failures:
     - python: 3.8-dev

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r test_requirements.txt

# command to run tests, e.g. python setup.py test
script: python setup.py test
